apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets-k8s
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://santjipandey3:0OSgFDk4IWKUUBR4@freelancedb.v0kbjfx.mongodb.net/?retryWrites=true&w=majority&appName=freelancedb"
  MONGODB_URL: "mongodb+srv://santjipandey3:0OSgFDk4IWKUUBR4@freelancedb.v0kbjfx.mongodb.net/?retryWrites=true&w=majority&appName=freelancedb"
  JWT_SECRET: "4391b51504f4a92c2d2d8f7f64231b22d72aa165295c089cc5ffc3a19e6413cb76487f8f179b1d03340e674db46164c93b5be8db5d9914b4687ff1661e3f61a"
  RAZORPAY_KEY_ID: "rzp_test_2jXh9BUuLKGW0e"
  RAZORPAY_KEY_SECRET: "4PaDeUHkqcN2IbcmurVwFeVt"
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets-k8s
type: Opaque
stringData:
  VITE_RAZORPAY_KEY: "rzp_test_2jXh9BUuLKGW0e"