apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-secrets-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "2fb90b9f-8316-4624-95d8-fcccec9070ea"
    keyvaultName: "freelance-app-kv-2025"
    tenantId: "2732182f-99fb-4517-b00c-951624afff93"
    objects: |
      array:
        - |
          objectName: mongodb-uri
          objectType: secret
          objectAlias: MONGODB_URI
        - |
          objectName: mongodb-uri
          objectType: secret
          objectAlias: MONGODB_URL
        - |
          objectName: jwt-secret
          objectType: secret
          objectAlias: JWT_SECRET
        - |
          objectName: razorpay-key-id
          objectType: secret
          objectAlias: RAZORPAY_KEY_ID
        - |
          objectName: razorpay-key-secret
          objectType: secret
          objectAlias: RAZORPAY_KEY_SECRET
        - |
          objectName: razorpay-key-id
          objectType: secret
          objectAlias: VITE_RAZORPAY_KEY
  secretObjects:
  - secretName: backend-secrets-k8s
    type: Opaque
    data:
    - objectName: MONGODB_URI
      key: MONGODB_URI
    - objectName: MONGODB_URL
      key: MONGODB_URL
    - objectName: JWT_SECRET
      key: JWT_SECRET
    - objectName: RAZORPAY_KEY_ID
      key: RAZORPAY_KEY_ID
    - objectName: RAZORPAY_KEY_SECRET
      key: RAZORPAY_KEY_SECRET
  - secretName: frontend-secrets-k8s
    type: Opaque
    data:
    - objectName: VITE_RAZORPAY_KEY
      key: VITE_RAZORPAY_KEY
