version: '3.8'

services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/freelance-frontend:latest
    ports:
      - "80:3000"  # Map port 80 to serve's port 3000 (NOT nginx port 80:80)
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: ${DOCKERHUB_USERNAME}/freelance-backend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - PORT=5000
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
