mode: deployment
resources:
  limits:
    memory: 256Mi
  requests:
    memory: 128Mi
config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  exporters:
    otlp:
      # This points directly to the Tempo service we just created
      endpoint: "tempo:4317"
      tls:
        insecure: true
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [otlp]
