apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: workload-identity-sa
      volumes: 
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true  
          volumeAttributes:
            secretProviderClass: "app-secrets-provider"
      containers:
      - name: frontend
        image: harshvardhan2003/freelance-frontend:0b6f16d51292191b4d3c3f6f4daa4da40523f992
        resources:
          requests:
            cpu: "50m"      # Reduced since no Node.js server
            memory: "64Mi"   # Nginx uses much less memory
          limits:
            cpu: "200m"
            memory: "128Mi"
        ports:
        - containerPort: 80  # Changed from 3000 to 80 (nginx default)
        env:
        - name: VITE_RAZORPAY_KEY
          valueFrom:
            secretKeyRef:
              name: frontend-secrets-k8s
              key: VITE_RAZORPAY_KEY
        volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets"
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # Changed from LoadBalancer to ClusterIP
