apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Backend non-sensitive configs
  REDIS_URI: "redis://redis-service:6379"
  JWT_EXPIRES_IN: "1d"
  PORT: "5000"
  NODE_ENV: "production"
  
  # Frontend non-sensitive configs  
  FRONTEND_URL: "https://yourapp.azurewebsites.net"  # Update for production
  VITE_API_URL: "https://api.yourapp.com/"           # Update for production
  REACT_APP_API_BASE_URL: "https://api.yourapp.com/api"  # Update for production
