apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: workload-identity-sa
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          volumeAttributes:
            secretProviderClass: "app-secrets-provider"
      containers:
      - name: backend
        image: harshvardhan2003/freelance-backend:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: backend-secrets-k8s
              key: MONGODB_URI
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: backend-secrets-k8s
              key: MONGODB_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets-k8s
              key: JWT_SECRET
        - name: RAZORPAY_KEY_ID
          valueFrom:
            secretKeyRef:
              name: backend-secrets-k8s
              key: RAZORPAY_KEY_ID
        - name: RAZORPAY_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets-k8s
              key: RAZORPAY_KEY_SECRET
        volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets-store"    # CHANGED: Standard path
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
